language: python

python:
 - pypy
 - pypy3
 - 2.6
 - 2.7
 - 3.2
 - 3.3
 - 3.4

install:
 - pip install coverage
 - if [ "$TRAVIS_PYTHON_VERSION" == "2.6" ]; then pip install unittest2; fi

script:
 - coverage run --source=schpy ./test_schpy.py -v

after_success:
 - pip install coveralls
 - coveralls

after_script:
 - coverage report
 - pip install pep8 pyflakes
 - pep8 --statistics --count *.py
 - pyflakes *.py | tee >(wc -l)

matrix:
  fast_finish: true
  allow_failures:
    - python: pypy
    - python: pypy3
    - python: 2.6
    - python: 2.6
    - python: 3.2
    - python: 3.3
    - python: 3.4
